name: Update CocoaPods

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Switch Xcode version
      run: sudo xcode-select -s /Applications/Xcode_11.app
    - name: Update CocoaPods dependences
      run: |
        pod update
        echo OK
