name: Update CocoaPods

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Switch Xcode version
      run: sudo xcode-select -s /Applications/Xcode_11.app
    - name: Update CocoaPods dependences
      run: sh pods-update.sh
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update CocoaPods dependences
        title: 'Update CocoaPods dependences'
