name: Create PR of update dependencies

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Switch Xcode version
      run: sudo xcode-select -s /Applications/Xcode_11.app
    - name: Update dependencies
      run: |
        pod update
        carthage update --platform iOS
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: 'Update dependencies'
